repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        # Only scan code/config directories, NOT docs or generated artifacts
        files: |
          ^(app/|db/|docker/|scripts/|\.github/|alembic\.ini|docker-compose.*\.yml)$
        exclude: |
          ^docs/|^backups/|^data/|^\.stack\.yml$|^\.env(\.docker)?$|^venv/|^\.venv/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        # Only scan first-party code trees; skip tests and virtualenvs
        args: ["-r", "app", "db", "scripts", "-x", "tests,venv,.venv"]
        pass_filenames: false
