# docker-compose.prod.yml
services:
  # Remove pgAdmin in prod overlay
  pgadmin: null

  postgres:
    image: postgres:16
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.max=10000
      - -c
      - pg_stat_statements.track=top
      - -c
      - pg_stat_statements.save=on
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # IMPORTANT: override base ports with an empty list (no host exposure)
    ports: []
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
      - .env.docker
    environment:
      ALEMBIC_CONFIG: /app/alembic.ini
      RUN_MIGRATIONS_ON_BOOT: "0"  # prod-like: skip on-boot migration
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
