name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit detect-secrets black flake8
      - name: Run pre-commit (format, lint, secret scan)
        run: |
          pre-commit run --all-files
