name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit detect-secrets black flake8 bandit

      - name: Run pre-commit (format, lint, secret scan)
        run: |
          pre-commit run --all-files

      - name: Security lint (Bandit)
        run: |
          bandit -r . -x tests

  unit-tests:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          # requirements.txt may be optional; proceed if missing
          pip install -r requirements.txt || true
          pip install pytest python-dotenv requests fastapi uvicorn

      - name: Run non-DB tests
        env:
          RUN_DB_TESTS: "0"
        run: |
          pytest -q tests/test_companies_house_client.py
          pytest -q tests/test_app_import.py

  db-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: detecktiv
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d detecktiv"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install DB test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest python-dotenv psycopg2-binary alembic sqlalchemy

      - name: Run DB tests (with Alembic migrations)
        env:
          RUN_DB_TESTS: "1"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: detecktiv
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: "5432"
        run: |
          pytest -q tests/test_companies.py
