name: Tests (Deps & Run)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps (pinned)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Show versions
        run: |
          python --version
          pip freeze | sort | sed -n '1,200p'

      # If your existing tests.yml already spins up Postgres and runs alembic,
      # this job can be kept simple, or you can add your DB steps here too.
      - name: Run tests
        run: |
          pytest -q
