name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }} # pragma: allowlist secret
          POSTGRES_DB: detecktiv
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d detecktiv"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }} # pragma: allowlist secret
      POSTGRES_DB: detecktiv
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: "5432"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" && break
            sleep 1
          done

      - name: Apply migrations
        run: |
          python -m alembic upgrade head

      - name: Run tests
        run: |
          pytest -q
